In [1]:
import canmatrix
import json

# Load the DBC file
db = canmatrix.loadp_flat('ApacheSparkGuide.dbc')

# Convert to JSON (which can be used in a Notebook)
with open('file.json', 'w') as f:
    json.dump(db, f)

ModuleNotFoundError: No module named 'canmatrix'

In [ ]:
pip install pyreadstat

In [6]:
import pandas as pd

import pyreadstat

df, meta = pyreadstat.read_sas7bdat('ApacheSparkGuide.dbc')

df.to_csv('file.csv')
# You can now load this CSV in a Jupyter Notebook

ReadstatError: Invalid file, or file has unsupported features

In [6]:
list = [1,2,3,4,5,6,7,8,9,10]
list.reverse()
print(list)

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [9]:
tuple = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
tuple = tuple[::-1]
print(tuple)        

(10, 9, 8, 7, 6, 5, 4, 3, 2, 1)


In [2]:

numbers = [55, 32, 87, 99, 10, 54, 32]
even = [num for num in numbers if num % 2 == 0]
odd = [num for num in numbers if num % 2 == 1]
print(odd)
print(even)

odd_squares = [(num, num * num) for num in numbers if num % 2 == 1]
print(odd_squares)

[55, 87, 99]
[32, 10, 54, 32]
[(55, 3025), (87, 7569), (99, 9801)]


Default Arguments / Keyword Arguments 
Default arguments are those arguments which can be changed but their value remains the same if not given. An example of the same is given below.


In [13]:
def double_the_number(num=1):
    return num * 2

print(double_the_number())

def double_the_number(num=1):
    return num * 2
print(double_the_number(5))

2
10


**Positional arguments** are those which are not followed by an equal sign (=) and default value. In this we need to provide an argument while calling the function, else we get an error. Here is an example below


In [3]:
def double_the_number(num):
    return num*2

print(double_the_number(1))
print(double_the_number(8))

2
16


In [3]:
my_Dict = {'a':1, 'b':2, 'c':3, 'd':4, 'e':5}
my_Dict.get('a', 0) 
             # Returns 1
# my_Dict.get('f', 0)  # Returns 0 since 'f' is not in the dictionary



1

In [16]:
def database_columns(*args):
    # for arg in args:
        print(args)

database_columns("name", "age", "height",'asdas', 'aasd')

('name', 'age', 'height', 'asdas', 'aasd')


In [ ]:
def database_columns(**args):
    for arg in args:
        print(arg)

database_columns(name="John", age=30, height=5.9, weight=70)

def database_columns(**kwargs):
    # for key, value in args.items():
    #     print(f"{key}: {value}")
    print(kwargs.keys())
    print(kwargs.values())
    print(kwargs.items())
    print(kwargs)
    p

database_columns(name="John", age=30, height=5.9, weight=70)




name
age
height
weight
dict_keys(['name', 'age', 'height', 'weight'])
dict_values(['John', 30, 5.9, 70])
dict_items([('name', 'John'), ('age', 30), ('height', 5.9), ('weight', 70)])
{'name': 'John', 'age': 30, 'height': 5.9, 'weight': 70}


**SYNTAX FOR MAP, FILTER, REDUCE** 

map(function, iterable)

In [47]:
my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

def num(n):
    if n % 2 == 0:
        return n

even = list(map(num, my_list))

print(even)



[None, 2, None, 4, None, 6, None, 8, None, 10]


In [46]:
# Filter
my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

def num(n):
    if n % 2 == 0:
        return n

even = tuple(filter(num, my_list))

print(even)

(2, 4, 6, 8, 10)


In [ ]:
### Enumerate

my_list = ['a', 'b', 'c', 'd', 'e']
for index, value in enumerate(my_list):
    # /print(value)
    print(index, value)


0 a
a
1 b
b
2 c
c
3 d
d
4 e
e


In [ ]:
class Student:
    # class variables
    school_name = 'ABC School'

    # constructor
    def __init__(self, name, age):
        # instance variables
        self.name = name
        self.age = age

    # instance variables
    def show(self):
        print(self.name, self.age, Student.school_name)

    @classmethod
    def change_School(self, name):
        self.school_name = name

    @staticmethod
    def find_notes(subject_name):
        subject_name = ['Math', 'Science', 'English']
        return ['chapter 1', 'chapter 2', 'chapter 3']
        print(subject_name)

# Example of a simple function
def greet(name):
    return f"Hello, {name}!"
# Example of a simple class
class Person:
    def __init__(self, name):
        self.name = name

    def introduce(self):
        return f"My name is {self.name}."
# Example of using the function and class


person = Person('alice')
print(greet(person.name))  # Output: Hello, alice!





Hello, alice!


In [19]:
darshil = Student('Darshil', 20)

# darshil.show()

darshil.find_notes(subject_name='Math')
darshil.change_School('XYZ School')

darshil.show()


Darshil 20 XYZ School


In [22]:
# 10 random integers upto 50 (exclusive). This makes the start value default to 0.
# The size parameter dictates the return array shape
import numpy as np
df = np.random.randint(50, size=(4,3))

print(df)


[[ 1 23  2]
 [46 26 34]
 [44 37 24]
 [21 24 23]]


In [ ]:
import numpy as np

# Create a 2D array with random integers
list = [1,2,3],[4,5,6],[7,8,9]
array_2d = np.array(list)
print(array_2d)

print(array_2d.shape)  # Output: (3, 3)
print(array_2d.dtype)  # Output: int64 (or int32 depending on the system)
# Accessing elements




[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
int32


In [ ]:
import numpy as np

# From list: 1d array
my_list = [10, 20, 30]
np.array(my_list)  # Convert list to numpy array
print(np.array(my_list))
# From tuple: 1d array
my_tuple = (10, 20, 30)
my = np.array(my_tuple)  # Convert tuple to numpy array
print(my) #
my.sjhape = (3, 1)  # Reshape to a 2D array with 3 rows and 1 column


[10 20 30]
[10 20 30]


In [33]:
list_of_lists =  [[5, 10, 15], [20, 25, 30], [35, 40, 45]]
twod_array = np.array(list_of_lists)

twod_array.shape

(3, 3)

In [35]:
# From list: 2d array
list_of_lists =  [[5, 10, 15], [20, 25, 30], [35, 40, 45]]
np.array(list_of_lists)
np.array(list_of_lists).shape  # Output: (3, 3)

(3, 3)

In [ ]:
d_array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(d_array.shape)  # Output: (2, 2, 2)
np.array(d_array)


(2, 2, 2)


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [2]:
import numpy as np

# 1D array
array_1d = np.array([1, 2, 3, 4, 5])
print("1D array:\n", array_1d)
print(array_1d.shape)

# 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D array:\n", array_2d)


# 3D array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D array:\n", array_3d)

1D array:
 [1 2 3 4 5]
(5,)

2D array:
 [[1 2 3]
 [4 5 6]]

3D array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
#creating a pandas series from a list
import pandas as pd

my_list = [10, 20, 30]
series = pd.Series(my_list)

print(series)
print(series.index)
print(series.values)

0    10
1    20
2    30
dtype: int64
RangeIndex(start=0, stop=3, step=1)
[10 20 30]


In [10]:
# creating a series from numPy Array
import numpy as np
import pandas as pd

index = ['a','b','c']
arr = np.array([10,20,30])

pd.Series(data=arr,index=index) 

# creating a series from dictionary
# import pandas as pd

# d = {'a':10, 'b':20, 'c':30}
# pd.Series(d)

a    10
b    20
c    30
dtype: int32

Note that dump() takes two positional arguments:

the data object to be serialized, and
the file-like object to which the bytes will be written.

In [1]:
import json

data = {
    "president": {
        "name": "Zaphod Beeblebrox",
        "species": "Betelgeusian"
    }
}

with open("data_file.json", "w") as write_file:
    json.dump(data, write_file)